name: openvista
services:
  maxkb:
    image: registry.fit2cloud.com/maxkb/maxkb
    container_name: openvista-maxkb
    ports:
      - "8080:8080"
    volumes:
      - openvista_maxkb_data:/opt/maxkb/model
      - openvista_maxkb_postgres:/var/lib/postgresql/data
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=MaxKB@123456
      - DB_NAME=maxkb
    restart: unless-stopped
volumes:
  openvista_maxkb_data:
    external: true
  openvista_maxkb_postgres:
    external: true
